version: 0.0
os: linux
files:
  - source: /demo-spring.jar
    destination: /tmp/code-package/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

branch_config:

  main:
    deploymentGroupName: CT_DEV_CD_GROUP
    deploymentGroupConfig:
      serviceRoleArn: arn:aws:iam::934247962179:role/CT_DEV_IAM_ROLE_CODE_DEPLOY
      ec2TagFilters:
        - { Type: KEY_AND_VALUE, Key: Environment, Value: dev }
    deploymentConfig:
      autoRollbackConfiguration:
        enabled: true