#!/bin/bash
service httpd start
pwd
nohup java -jar /tmp/code/demo-spring.jar --spring.datasource.url=jdbc:mysql://casualtalent-dev.c5asdskod118.ap-southeast-2.rds.amazonaws.com:3306/casualtalent >/dev/null 2>&1 &
ps -ef | grep java
